No energy distribution found

### Collecting Energy Distribution Data
    0Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 1979, in <module>
    simulation.generate_energy_distribution_data(Nruns_per_energy=1000) # originally 10000
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 671, in generate_energy_distribution_data
    wvl_dict, xy_dict, _, _ = self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 306, in read_output
    vol_debug = np.array(debug["volume"].array())
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/uproot/behaviors/TBranch.py", line 1647, in __getitem__
    raise uproot.KeyInFileError(
uproot.exceptions.KeyInFileError: not found: 'volume'

    Available keys: 'vZ', 'wlen', 'fEvent', 'process'

in file /home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main/build/output0.root
in object /Debug;1
