Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 336, in <module>
    os.mkdir(directory + "/data/" + identifier)
FileNotFoundError: [Errno 2] No such file or directory: '/home/minseokhwan/xray_projects/xray_scattering_discrimination/data/YAGCe_150keV'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
Traceback (most recent call last):
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
Traceback (most recent call last):
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
NameError: name 'plt' is not defined
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
NameError: name 'plt' is not defined
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
NameError: name 'plt' is not defined
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
Traceback (most recent call last):
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 338, in <module>
    simulation = geant4(G4directory = "/home/minseokhwan/xray_projects/geant4/G4_Nanophotonic_Scintillator-main",
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 83, in __init__
    fig, ax = plt.subplots(1, 1, figsize=[16,12], dpi=300)
NameError: name 'plt' is not defined
